### ISSUE TITLE
Generated SURTs are invalid

### ISSUE THREAD

**Issue by ibnesayeed** [machawk1/cdxjGenerator#4]
I was experimenting with this and noted a few issues and opportunities for potential improvements:

- [X] Default output (without a custom providedURIR) does not generate SURTs with `)` host and path separator (#8)
- [X] Original URI does not have a trailing slash
- [x] Occasionally empty host is generated like `http://.catering` (about 4% of the total) (#7)
- [x] Can use f-string instead of template substitution (#5) 26735be
- [ ] You may want to remove custom providedURIR parameter from the generator function, and if you need it, you can create a separate function for it, as it will simplify the logic and conditionals and will improve the performance as well
- [X] In the README file, change `sort` to `LC_ALL=C sort` 0aee785ed77c97fbca8c6cb1b519de4aeb530064

**Comment by machawk1** [comment]
@ibnesayeed Thank you very much for having a look and testing out the tool. I appreciate your feedback as an authoritative source on the format. I will break out each of these tasks into separate issues and hopefully you will be willing to review improved versions.
